//
//  MessagesViewController.m
//  MessagesExtension
//
//  Created by Zac on 2017/2/13.
//  Copyright © 2017年 Zac. All rights reserved.
//

#import "MessagesViewController.h"
#import "SlideTabViewController.h"
#import "Masonry.h"

@interface MessagesViewController ()
/*
 *页面布局参考海豚浏览器
 */
@property (nonatomic, strong) UITextField *searchTextField;
@property (nonatomic, strong) UIButton *resignSearchBtn;
@property (nonatomic, strong) SlideTabViewController *slidTabVC;

@end

@implementation MessagesViewController
#pragma mark - Static Var
static topInset = 80 + 10;//联系人名字那一块是80
static horizontalInset = 8;
static height4SearchTextField = 33;
static width4ResignSearchBtn = 30;
//有按钮的情况
/*
 *|
 *| 8 <TextField> 3 <Btn> 8 |
 *|       slideTabVC        |
 *|                         |
 *
 */
static leftInset4SearchTextField = 8;
static rightInset4SearchTextField = 3;
static rightInset4ResignSearchBtn = 8;

//size

#pragma mark - Lifecycle
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    self.searchTextField = [[UITextField alloc]init];
    [self.view addSubview:self.searchTextField];
    
    self.resignSearchBtn = [UIButton buttonWithType:UIButtonTypeCustom];
    [self.resignSearchBtn setImage:[UIImage imageNamed:@"resignSearchBtnPic"]
                          forState:UIControlStateNormal];
    [self.resignSearchBtn addTarget:self
                             action:@selector(handleResignSearchBtn)
                   forControlEvents:UIControlEventTouchUpInside];
    [self.view addSubview:self.resignSearchBtn];
    
    [self setUpLayout];
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

#pragma mark - Conversation Handling

-(void)didBecomeActiveWithConversation:(MSConversation *)conversation {
    // Called when the extension is about to move from the inactive to active state.
    // This will happen when the extension is about to present UI.
    
    // Use this method to configure the extension and restore previously stored state.
}

-(void)willResignActiveWithConversation:(MSConversation *)conversation {
    // Called when the extension is about to move from the active to inactive state.
    // This will happen when the user dissmises the extension, changes to a different
    // conversation or quits Messages.
    
    // Use this method to release shared resources, save user data, invalidate timers,
    // and store enough state information to restore your extension to its current state
    // in case it is terminated later.
}

-(void)didReceiveMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when a message arrives that was generated by another instance of this
    // extension on a remote device.
    
    // Use this method to trigger UI updates in response to the message.
}

-(void)didStartSendingMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when the user taps the send button.
}

-(void)didCancelSendingMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when the user deletes the message without sending it.
    
    // Use this to clean up state related to the deleted message.
}

-(void)willTransitionToPresentationStyle:(MSMessagesAppPresentationStyle)presentationStyle {
    // Called before the extension transitions to a new presentation style.
    
    // Use this method to prepare for the change in presentation style.
    if (presentationStyle == MSMessagesAppPresentationStyleExpanded) {
        NSLog(@"展开来");
        [self upDateLayout];
    }
}

-(void)didTransitionToPresentationStyle:(MSMessagesAppPresentationStyle)presentationStyle {
    // Called after the extension transitions to a new presentation style.
    // Use this method to finalize any behaviors associated with the change in presentation style.
    
}
#pragma mark - Handlers
- (void)handleResignSearchBtn
{
    
}
#pragma mark - Layout
- (void)setUpLayout
{
    self.searchTextField.alignmentRectInsets = UIEdgeInsetsMake(0, 3, 0, 0);
    self.searchTextField.placeholder = @"Search or type URL";
    
    [self.searchTextField mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.mas_equalTo(self.view.mas_top).offset(topInset);
        make.left.mas_equalTo(self.view.mas_left).offset(horizontalInset);
        make.right.mas_equalTo(self.view.mas_right).offset(horizontalInset);
        make.height.mas_equalTo(height4SearchTextField);
    }];
    
    
    [self.resignSearchBtn mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.mas_equalTo(self.view.mas_top).offset(topInset);
        make.left.mas_equalTo(self.view.mas_right).offset(0);
        make.height.mas_equalTo(height4SearchTextField);
        make.width.mas_equalTo(0);
    }]
}

- (void)upDateLayout
{
    self.searchTextField.alignmentRectInsets = UIEdgeInsetsMake(0, 3, 0, width4ResignSearchBtn);
    
    [self.view layoutIfNeeded];
    [UIView animateWithDuration:1.0 animations:^{
        self.resignSearchBtn.transform = CGAffineTransformMakeTranslation(-width4ResignSearchBtn, 0);
    }];
}
@end
